apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathutils-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mathutils
  template:
    metadata:
      labels:
        app: mathutils
    spec:
      containers:
      - name: mathutils
        image: roguemain12/math-utils:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mathutils-service
spec:
  type: LoadBalancer
  selector:
    app: mathutils
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
